[collectibles]
type = "tileset"

[collectibles.animations.balloons-on-ground]
from = ["balloons[0-9]*.png"]
duration = 3000

[collectibles.animations.balloons-red-fly]
from = ["balloon-red-fly[0-9]*.png"]
duration = 800